# Generated by Django 3.2.7 on 2021-09-13 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=1000)),
                ('autor', models.CharField(max_length=200)),
                ('adicionado', models.DateField(auto_now_add=True)),
                ('concluido', models.DateField(blank=True, null=True)),
                ('nota', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
    ]
