# Generated by Django 3.2.7 on 2021-09-11 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=6000)),
                ('autor', models.CharField(max_length=1)),
                ('adicionado', models.DateField(auto_now_add=True)),
                ('concluido', models.DateField(blank=True)),
                ('nota', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
